[env:CDEBYTE_EoRa-Hub]
extends = esp32s3_base
platform_packages =
    platformio/framework-arduinoespressif32 @ https://github.com/m1nl/esp32-arduino-lib-builder/releases/download/v2.x-1f03867-3240598/framework-arduinoespressif32-v2.x-1f03867-3240598.tar.gz
board = CDEBYTE_EoRa-Hub
board_level = extra
build_flags =
  ${esp32s3_base.build_flags}
  -D PRIVATE_HW
  -D OLED_RU
  -I variants/esp32s3/CDEBYTE_EoRa-Hub
